import Head from 'next/head';
import {GetServerSideProps} from 'next'
import { useEffect } from 'react';

const MenuEnabledCategories = [28, 8, 50, 16]

export default function Home({data}) {

  return (
    <div>
      <Head>
        <title>Cris Barros - Projeto</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
      </main>
    </div>
  );
}

//getStaticProps

export const getServerSideProps: GetServerSideProps = async () => {
  return{
    props: {
    }
  }
}
